name: Swift
on: [push]
jobs:
  test:
    name: Launch swift test
    runs-on: macos-latest

    steps:
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_12.3.app/Contents/Developer
        xcodebuild -version

    - uses: actions/checkout@v1

    - name: Launch tests
      run: |
        swift test

  docker:
    name: 'Hello World'
    description: 'Greet someone and record the time'
    runs:
      using: 'docker'
      image: 'Dockerfile'

