name: Swift

on: [push]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
        xcodebuild -version

    - uses: actions/checkout@v1

    - name: Launch tests
      run: |
        swift test
