#if !canImport(ObjectiveC)
import XCTest

extension thingsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__thingsTests = [
        ("testFailureEmpty", testFailureEmpty),
        ("testFailureWithoutTitle", testFailureWithoutTitle),
        ("testSuccessOneTodo", testSuccessOneTodo),
        ("testSuccessOnlyTitle", testSuccessOnlyTitle),
        ("testSuccessTwoTodo", testSuccessTwoTodo),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(thingsTests.__allTests__thingsTests),
    ]
}
#endif
